### ISSUE TITLE
Unicode characters not being properly displayed in JTextArea

### ISSUE THREAD

**Issue by raquel-ucl** [UCL-RITS/nammu#28]
When reading an ATF file and printing it out in the terminal, I get the correct content of my text file Belsunu.atf, e.g.:

```
#lem: šatti[year]N; n; Ṭebetu[1]MN; mūša[at night]AV; ūm[day]N; n
```

But when printing the same text in a JTextArea, I get this instead:

```
#lem: Å¡atti[year]N; n; á¹¬ebetu[1]MN; mÅ«Å¡a[at night]AV; Å«m[day]N; n
```

This is the code dealing with opening ATF files and displaying them in the text area:

__MainController.py__
```python
    def openFile(self):
        fileChooser = JFileChooser()
        filter = FileNameExtensionFilter("ATF files", ["atf"])
        fileChooser.setFileFilter(filter)
        status = fileChooser.showDialog(self.view, "Choose file")
        
        if status == JFileChooser.APPROVE_OPTION:
            atfFile = fileChooser.getSelectedFile()
            atfText = self.readTextFile(atfFile)
            self.atfAreaController.setAtfAreaText(atfText)
            print atfText

    def readTextFile(self, file):
        filename = file.getCanonicalPath()
        f = open(filename, "r")
        text = f.read()
        return text
        #TODO: Check if selected file is ATF or at least text file!

```

__AtfAreaController.py__
```python
    def setAtfAreaText(self, text):
        self.view.editArea.setText(text)
```

**Comment by stinney** [comment]
Hi, Raquel, great to see you working on this!

If you are stumped by this one let me know.

 Steve

**Comment by raquel-ucl** [comment]
Hi Steve!

Yes, I'm a bit stuck on this one. Do you have any ideas? I did a little research and found it could be the font, but it's the same one that is working properly on the terminal. Maybe it's a matter of decoding and re-encoding the string before printing the text in the text area, but it seems to work when I print on the terminal, so I don't think that helps. 

I'll go on with the development, I was aiming to send you all a jar with Nammu having basic file edition functionality before I went on holidays, but couldn't because I started one more project and it all became a bit too busy! I came back from holidays this Tuesday, and I wanted to just do ORACC until I get that jar done!

**Comment by stinney** [comment]
Yeah I think I can help with this as it happens.

I think what you are looking at is the raw UTF-8 text so it's not the font but the way the terminal is displaying Unicode.

The general solution is that you need to tell the API or the application to use the UTF-8 encoding (encoding, charset or the like).

When ATF is in Unicide it is always encoded in UTF-8 so if would be best to do this in the application but you may need to do it by setting a variable somewhere.

 Steve

**Comment by raquel-ucl** [comment]
Thanks! It helped me solve the problem.

I found a Python library that open files and encodes/decodes them in UTF-8. So now my code works and the text is displayed properly in the JTextArea. This was before:

```python
f = open(filename, "r")
text = f.read()
```

And this is what fixed it:

```python
text = codecs.open(filename, encoding='utf-8').read()
```
