### ISSUE TITLE
Test connection to server for lemmatization

### ISSUE THREAD

**Issue by raquel-ucl** [UCL-RITS/nammu#4]
Remind Steve to send Raquel an email with the connection details and/or permissions on the server code in Github when made public (“oman” project?)
It was clarified that the query to the server requires the whole ATF file as input, which is then processed in the server (lemmata are added, and if they already had been, then checks for “x” chars and re-lemmatize) and returns the resultant ATF file to the client..
Write a short piece of code to try out connection once Steve sends the details to confirm everything works as expected.

**Comment by raquel-ucl** [comment]
Working on this at the moment.

I found in [the code of the Emacs plugin currently in use](http://oracc.museum.upenn.edu/downloads/atf-mode.zip) some code that can be of help. In the `atf-model.el` file there is an XML-RCP connection to `http://oracc.museum.upenn.edu/cgi-bin/rpc` with three arguments:

* data - I think this is the ATF text
* aft-file-name 
* atf-args - Unclear, need to investigate

I have found [a python library for XML-RCP](http://www.jython.org/docs/library/xmlrpclib.html) that I can use from the Jython code. However, I'd have to use an old version of it due to Jython using Python<3.0, so I'm going to explore [the Java option](http://www.tutorialspoint.com/xml-rpc/xml_rpc_examples.htm) since I can use that from Jython as well, in theory.

**Comment by raquel-ucl** [comment]
I've made a small example on the python library for XML-RCP [here](https://github.com/raquel-ucl/xml-rcp-example).

Steve T has come back to me about this and prefers to postpone until we talk about the different options for this next week.

**Comment by raquel-ucl** [comment]
Steve gave me a few hints and a link to [this repo](https://github.com/oracc/osys) to look at before the call next week. 

* We won't use the XML-RPC connection but the SOAP one instead. 

* The client will send a zip file and some arguments to the server and this will return another zip file to the client. The lemmatisation functionality is not yet live in that server, but Steve will work on that next week.

* In the OSYS repo there is a file called [osc-pack.h](https://github.com/oracc/osys/blob/master/osc/osc-pack.sh) that generates the zip that is sent to the server. Looking inside that, it accepts the following options that I'm assuming can be mapped to the existing server and that I might need to implement in Nammu:
 * build
    * corpus
    * portal
 * check
 * config
 * harvest
 * merge 
 * pdf
 * resources

* In the OSYS repo there is a file called [osc.c](https://github.com/oracc/osys/blob/master/osc/osc.c) that imports [osc-base](https://github.com/oracc/osys/blob/master/osc/osc-base.c) which I think is somehow related to [osc-lib.c](https://github.com/oracc/osys/blob/master/osc/osc-lib.c.in), which can give me an idea of how to write a client for the server.

**Comment by raquel-ucl** [comment]
Looking at the code, I find lots of references to http://oracc.org/wsdl/ows.wsdl which is not live or in the repo. What I found was [osc.wsdl](https://github.com/oracc/osys/blob/master/osc/osc.wsdl), that is probably similar to ORACC's WSDL. 

I'm working with some WSDL functionality in python. I'm created a small sample repo [here](https://github.com/raquel-ucl/SOAPpy-example) with a SOAP client and several WSDL files. It creates a proxy pointing to given file and prints out available methods and their arguments.

**Comment by raquel-ucl** [comment]
Turns out SOAPpy is a bit outdated and I've run into a couple problems. It works fine to list methods, args, etc. but actually using them doesn't work.

I've found another python module called [suds](https://fedorahosted.org/suds/wiki/Documentation) that actually works :) 

I'll create some examples to investigate how to use for when I get the right URL to ORACC's WSDL file.

**Comment by stinney** [comment]
This is great: when we talk next week we can figure out what a good URL would be--I confess I did not realise I needed to expose that via a URL but it makes sense I guess ...

All the best,

 Steve

**Comment by raquel-ucl** [comment]
Sure! I thought the URL was supposed to be something like http://oracc.org/wsdl/ows.wsdl  since there's several references to it in the [OSYS](https://github.com/oracc/osys/tree/master/osc) code. It seems down, maybe it's been moved? Or maybe we need to create a new wsdl file for ORACC's gSOAP server. Let's discuss next week. I'll email you with some options.

**Comment by stinney** [comment]
I wasn't sure without looking if that was just a namespace or if it was supposed to be possible to dereference the URL 

If it is supposed to exist I can easily arrange that: we just have to be sure which of the soap files should live at the end of the URL

All the best

 Steve

**Comment by raquel-ucl** [comment]
Great! I think maybe [osc.wsdl](https://github.com/oracc/osys/blob/master/osc/osc.wsdl) is the one we need to use and we should expose it in http://oracc.org/wsdl/osc.wsdl. I will need your help to check if the methods it contains are enough or which methods should go in it. It is also referencing `osc_data.xsd` and `osc_meth.xsd`, so those will also probably be needed.

**Comment by raquel-ucl** [comment]
I've made [a sample repo](https://github.com/raquel-ucl/suds-example/blob/master/README.md) to learn to use Python SUDS. 

I've realised the WSDL file doesn't actually need to be exposed via URL, it can just be stored locally. 

I've also realised the Python SUDS library is outdated, but luckily there's a project called SUDS-jurko that is being actively maintained and works fine. It seems to load the osc.wsdl file without any problems, I just need to know the location of the SOAP server to test the methods. In the WSDL it assumes I'm running the server on my localhost, but I'm not.

**Comment by raquel-ucl** [comment]
I had a Skype call with Steve and found out the location of the remote server is http://oracc.museum.upenn.edu:8085

These are two methods I need to use:

```
            Request(Request Request, xs:base64Binary Attachments)
            Response(Response Response, xs:base64Binary Attachments)
```

These need Request and Response object, which are complex data types. SUDS has an object factory to create a template of these objects very easily that I can use to build the objects:

```python
from suds.client import Client
url = "file:///Users/raquel/workspace/training/Jython/soap/SOAPpy/wsdl/osc.wsdl"
oracc_client = Client(url)
request = client.factory.create('Request')
response = client.factory.create('Response')
```

Which creates:

```
(Request){
   keys =
      (Keys){
         key[] = <empty>
      }
   data =
      (DataSet){
         item[] = <empty>
      }
 }

```

and:

```
(Response){
   keys =
      (Keys){
         key[] = <empty>
      }
 }
```

This is not enough, but it's a start. To fill in the gaps, it's good to have a look at:

* [osc.wsdl](https://github.com/oracc/osys/blob/master/osc/osc.wsdl), [osc_data.xsd](https://github.com/oracc/osys/blob/master/osc/osc_data.xsd) and [osc_meth.xsd](https://github.com/oracc/osys/blob/master/osc/osc_meth.xsd), which have the definition of the data types.
* [oracc.in](https://github.com/oracc/osys/blob/master/osc/oracc.in): Perl script that contains the login of the request-response process and calls the `osc` client with arguments depending on the functionality we want. Focus on the `atf` command (i.e. validation), see `} elsif ($command eq 'atf' || $command eq 'lem') {` etc., and the wait loop. 
* [osc-pack.sh](https://github.com/oracc/osys/blob/master/osc/osc-pack.sh), although we are focusing on the validations functionality by now, not the lemmatisation, which doesn't really need any packing.
* [osc-lib.c.in](https://github.com/oracc/osys/blob/master/osc/osc-lib.c.in), specially  the `int run_client(int argc, char **argv)` method.

**Comment by raquel-ucl** [comment]
I was trying to send a Request object + attachments to the server and run into problems.

This is the service signature:

```
Request(Request Request, xs:base64Binary Attachments)
```

I have created a Request object for `Belsunu.atf` by zipping it as `request.zip`. I then encoded it in base64:

```
request.keys = ["atf", "cams/gkab"]

with open("request.zip", "rb") as f:
    encoded = base64.b64encode(f.read())
```

When I try to send the Request like this:

```
client.service.Request(request, encoded)
```

it returns this error message:

```
Validation constraint violation: tag name or namespace mismatch in element 'Attachments'
```

Looking in the SOAP envelope to see what is actually being sent to the server, this is what I find:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://oracc.org/wsdl/ows.wsdl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
        <ns0:Body>
            <ns1:Request>
               <keys>atf</keys>
               <keys>cams/gafk</keys>
            </ns1:Request>     
            <Attachments>UEsD...AAA=</Attachments>
        </ns0:Body>
</SOAP-ENV:Envelope>
```

It seems to be complaining because the "Attachments" doesn't have any namespace preceding it. It would help enormously if we could have a SOAP envelope from an actual working Request. Could you send us one, @stinney?

**Comment by raquel-ucl** [comment]
Steve has followed [the gSOAP instructions to set up debugging](https://www.cs.fsu.edu/~engelen/soapdoc2.html#tth_sEc9.14) and sent the logs.

The "SENT.log" file from the debug Steve sent shows this SOAP envelop that differs from mine one:

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:xmime5="http://www.w3.org/2005/05/xmlmime" xmlns:osc-data="http://oracc.org/wsdl/ows.xsd" xmlns:osc-meth="http://oracc.org/wsdl/ows.wsdl">
    <SOAP-ENV:Body>
        <osc-meth:Request>
            <osc-data:keys>
                <osc-data:key>atf</osc-data:key>
                <osc-data:key>tests/mini</osc-data:key>
                <osc-data:key>00atf/hyphens.atf</osc-data:key>
           </osc-data:keys>
           <osc-data:data>
                <osc-data:item xmime5:contentType="*/*">
                    <xop:Include href="cid:id6"/>
                </osc-data:item>
            </osc-data:data>
        </osc-meth:Request>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Needs some investigating on how to make my request look like the one from Steve.

**Comment by raquel-ucl** [comment]
After some investigating, I found how the file is being transferred.

I assumed from the Request created by the suds' client factory that it was part of the SOAP envelope, but it actually isn't. It uses a mechanism called SOAP MTOM (Message Transmission Optimization Mechanism) which attaches the file in the HTTP message and references it from the SOAP envelope, trying to make the SOAP envelop smaller. 

In Steve examples, `id6` is pointing to the Content-ID element in the HTTP request:

```
Content-Type: */*
Content-Transfer-Encoding: binary
Content-ID: <id6>

PK¤AtG.ÕUen00atf/hyphens.atfUT	cOVJOVuxõS04AÛ.å¢ü¬Ôä+ÔâbýÜÌ¼L.åÄ4+ÒâTÒ¼ÌäüT.¨PNb^ºBEi¡BuNé£¦¦ÚDÝ¤LÝ¢R.åÔ\+íÄ¤Ì¢Òh0ë§ÂPK¤AtG.ÕUen 00atf/hyphens.atfUTcOVuxõPKW°
--==nGpzR/KspN6ry7jG8CU4bonN2aujzfJamyN3xYjaldFXYpeUryNGb0UROC0B==--

POST / HTTP/1.1
Host: localhost:8085
User-Agent: gSOAP/2.8
Content-Type: application/soap+xml; charset=utf-8
Content-Length: 623
Connection: close

```

* `suds` can't deal with this kind of SOAP messages, so I have to find another python library to do this, although there didn't seem to be many in the first place. Not much hope on this option.
* There might be a way to create the HTTP request with Python in some other way.
* I can also look into Java libraries, although everything SOAP-related for Java has documentation dated 2007-2010. I have tried a couple examples with JAWS-WS, but the documentation was outdated compared with the packages content.

I'll have a look around and see how to do this.

**Comment by raquel-ucl** [comment]
I had to discard suds as well as other SOAP libraries I tried in Python and Java because some of them are deprecated and the others don't support multipart/related requests like the ones the ORACC server expects.

The way to resolve this was to create the HTTP message from scratch using MIME objects. Each part of the three sections of the request is a MIME object. [MIMEMultipart](https://docs.python.org/2/library/email.mime.html#email.mime.multipart.MIMEMultipart) represents the parent object that has a [MIMEApplication](https://docs.python.org/2/library/email.mime.html#email.mime.application.MIMEApplication) attached. The MIMEApplication message contains the SOAP Envelope and the reference to the binary payload that contains the request.zip file encoded in a [MIMEBase](https://docs.python.org/2/library/email.mime.html#email.mime.base.MIMEBase) object. This is how the message looks like for the example file sent by Steve:

```
Content-Type: multipart/related; charset="utf-8"; type="application/xop+xml";
 start="<SOAP-ENV:Envelope>"; start-info="application/soap+xml";
 boundary="===============0821753454=="
Host: http://oracc.museum.upenn.edu:8085
Content-Length: 1500
Connection: close

--===============0821753454==
MIME-Version: 1.0
Content-ID: <SOAP-ENV:Envelope>
Content-Transfer-Encoding: binary
Content-Type: application/xop+xml; charset="utf-8"; type="application/soap+xml"

<?xml version="1.0" encoding="UTF-8"?>
            <SOAP-ENV:Envelope
                xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope"
                xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xop="http://www.w3.org/2004/08/xop/include"
                xmlns:xmime5="http://www.w3.org/2005/05/xmlmime"
                xmlns:osc-data="http://oracc.org/wsdl/ows.xsd"
                xmlns:osc-meth="http://oracc.org/wsdl/ows.wsdl">
                <SOAP-ENV:Body>
                    <osc-meth:Request>
                        <osc-data:keys>
                            <osc-data:key>atf</osc-data:key><osc-data:key>tests/mini</osc-data:key><osc-data:key>00atf/hyphens.atf</osc-data:key>
                        </osc-data:keys>
                        <osc-data:data>
                            <osc-data:item xmime5:contentType="*/*">
                                <xop:Include href="cid:request_zip"/>
                            </osc-data:item>
                        </osc-data:data>
                    </osc-meth:Request>
                </SOAP-ENV:Body>
            </SOAP-ENV:Envelope>
--===============0821753454==
Content-Type: */*
MIME-Version: 1.0
Content-ID: <request_zip>
Content-Transfer-Encoding: binary

P�AtG.�Uen00atf/hyphens.atfUT	cOVJOVux
                                        �S
                                          04A.傢���+����b��L.�Ē4+���T�Ҽ���T.�PNb^�BEi���BuN飦�ڌDݤLݢR.��\+�Ĥ̢�h0��P�AtG.�Uen��00atf/hyphens.atfUTcOVux
                    �PKW�
--===============0821753454==--
```

Note most of the headers and parameters need to be set or modified by hand because they are not the default ones MIME creates.

This message is then sent to the ORACC server using the python [requests](http://docs.python-requests.org/en/master/) library. I also tried urllib, urllib2, httplib, etc., but requests was the only one that worked at the time and seems cleaner than the others.

I run into several problems trying to make this work, most notably the library I was using was replacing the `\r\n` line endings with `\n` which made the server confused. To find this out, I had to use a logging library that'd print out the HTTP request including line endings and [httpbin](https://httpbin.org) to check I'm sending the server what I think I'm sending, for example like this:

```
import requests
import logging
import httplib as http_client
http_client.HTTPConnection.debuglevel = 1
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True

#Test
requests.get('https://httpbin.org/headers')
```

Once the file is received by the server, this sends a SOAP response with the ID of the request, like this:

```

```

Then we send a HTTP GET message to the server in `http://oracc.museum.upenn.edu/p/<ID>` (note no :8085 port). When we retrieve a "Done" string from this request, we get ready to grab the response from the server, which is a zip file containing two logs with the validation messages. To grab the response we need to create another MIMEApplication object with a SOAP Envelope that looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:xmime5="http://www.w3.org/2005/05/xmlmime" xmlns:osc-data="http://oracc.org/wsdl/ows.xsd" xmlns:osc-meth="http://oracc.org/wsdl/ows.wsdl">
   <SOAP-ENV:Body>
       <osc-meth:Response>
          <osc-data:keys>
            <osc-data:key>ZO3vNg</osc-data:key>
          </osc-data:keys>
      </osc-meth:Response>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

This returns a response from the server that looks like this:

```
--==xW4ythRAPcd4moqXclkPetofv8LdI5m5Per9/89PYbH+DxWfW6u0oXTXTe1b==\r\n
Content-Type: application/xop+xml; charset=utf-8; type="application/soap+xml"\r\nContent-Transfer-Encoding: binary\r\nContent-ID: <SOAP-ENV:Envelope>\r\n\r\n
<?xml version="1.0" encoding="UTF-8"?>\n
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:xmime5="http://www.w3.org/2005/05/xmlmime" xmlns:osc-data="http://oracc.org/wsdl/ows.xsd" xmlns:osc-meth="http://oracc.org/wsdl/ows.wsdl">
 <SOAP-ENV:Body>
   <osc-meth:ResponseResponse>
     <osc-data:keys>
        <osc-data:key>done</osc-data:key>
     </osc-data:keys>
     <osc-data:data>
       <osc-data:item xmime5:contentType="*/*">
         <xop:Include href="cid:id2"/> 
        </osc-data:item>
      </osc-data:data>
    </osc-meth:ResponseResponse>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>\r\n\r\n
--==xW4ythRAPcd4moqXclkPetofv8LdI5m5Per9/89PYbH+DxWfW6u0oXTXTe1b==\r\n
Content-Type: */*\r\n
Content-Transfer-Encoding: binary\r\n
Content-ID: <id2>\r\n\r\n
PK\x03\x04\x14\x00\x00\x00\x08\x00\x1bGjH\xaf8\xca\x1c8\x01\x00\x00\x15\x03\x00\x00\x0b\x00\x1c\x00request.logUT\t\x00\x03&}\xe1V&}\xe1Vux\x0b\x00\x01\x040\x00\x00\x00\x04\xf5\x01\x00\x00\xa5\x91\xc1n\xc20\x0c\x86\xef}\n\xbf@\x9b\xc2i\xea\xb4\xc3\xa4\x9d9\x8c\xcb$4\xa1\x90\xba4\x90\xc6Y\x1c\xda\xb2\xa7_\xda\x8a\x81\x06C\x93\x96S\xe4\xfc\xfe~\xfb\x0fy\xa9T\x8a=\xaa\x8c\xeb\xd5\xfc\xbd\x80\xf6\xf5a\xbb\x9c\x81\x08\x8d\x13\xa5\x0cro\x16\xcb\xe5\x1b\xc8PA@\x0e,\x1am5\xe4y,\x88\xfa\xe8j\xb4\x9c\xc5{Bg\x923\xfd\xaa\xcd\xf3\xd9\x7fi\xeb\x81V\x80\xeb\xca\'QS\x83b\xac\x8e,&\'&v\xd2\xf3\x91\x036p)\xe1\x8d\xb6\x82X\xa5\xca\xa3\x0c\x18w;MrvMb\x93+\xb5\xbf\xc3~\x04\xe7iw\xa59#&\xfczP\xa1\np[u\xe9\xa96%\xc8*\xa0\x07\x8f\r\xb5\xdan\xc1h\xbb\x87\xe8\xc1\x89\xe1\x02\x94\xb4\x96\x02D\x022C>\xef\xbaN\xc4\xa6\x02\x16\x04|P5T\xda \x90\x1f:\xa2%\xf9\xe3w\x00\x07\xfb\xa9\xdd\xcf\xa8\x93g\xafj\xddb\x01W/\x00\xdaVF\x868Dq\xfd\x050\x9d\x9b\xf1\x8e\xe9\xf6\x90\x1a\xf8=\xbb\xa9\x98\x19\xdaB\xaa\xda\xe6\xe5\xc6\'\x9f\xd0\xc3\xd8\xe9\xee\x1e\xcb#;\xb2\x8c\xd9\xb8\xe1=\xdd\xc7!\x86=\xba\xfee\xb4\x98\x81,\xcb1\x80\x8b\xd6/PK\x03\x04\x14\x00\x00\x00\x08\x00\x1bGjH\x97\xbf\x03\xc3}\x00\x00\x00\x98\x00\x00\x00\t\x00\x1c\x00oracc.logUT\t\x00\x03&}\xe1V&}\xe1Vux\x0b\x00\x01\x04\x00\x00\x00\x00\x04\xf5\x01\x00\x00\x1d\x8b\xb1\x0e\xc3 \x0cD\xf7|\x85\xbf &\x19\xd9\xbat\xee\xd0\xbd\xa2`\x02R\xb0#LT\xfa\xf7%\xd5-w\xf7\xee\x8cq-b\xfa\x1e\x89X\xe7\xe1\xedj\x1f\xcbz\xc9B?\xc2+sn\x160I!\x94\xea\xbc\xc7^vl\xa4M\xb1\x0c\x88^8\xe6m\x1e-\xb04\x88rr\x00\xa9\xffP\xc9\x05\xf7\xdei\xba=\xefpT\xf1\xa4:\x90t\xc8\xaa\'\x05X\xe0\xe3*g\xde\x14\xdc\xb8\x99\xeb\x95\xc7j\xfa\x01PK\x01\x02\x1e\x03\x14\x00\x00\x00\x08\x00\x1bGjH\xaf8\xca\x1c8\x01\x00\x00\x15\x03\x00\x00\x0b\x00\x18\x00\x00\x00\x00\x00\x01\x00\x00\x00\x80\x81\x00\x00\x00\x00request.logUT\x05\x00\x03&}\xe1Vux\x0b\x00\x01\x040\x00\x00\x00\x04\xf5\x01\x00\x00PK\x01\x02\x1e\x03\x14\x00\x00\x00\x08\x00\x1bGjH\x97\xbf\x03\xc3}\x00\x00\x00\x98\x00\x00\x00\t\x00\x18\x00\x00\x00\x00\x00\x01\x00\x00\x00\xb6\x81}\x01\x00\x00oracc.logUT\x05\x00\x03&}\xe1Vux\x0b\x00\x01\x04\x00\x00\x00\x00\x04\xf5\x01\x00\x00PK\x05\x06\x00\x00\x00\x00\x02\x00\x02\x00\xa0\x00\x00\x00=\x02\x00\x00\x00\x00\r\n
--==xW4ythRAPcd4moqXclkPetofv8LdI5m5Per9/89PYbH+DxWfW6u0oXTXTe1b==--

```

We need to read the binary payload, which is an encoded zip file, into a bytearray, then extract the zip into a dictionary and retrieve the content of `oracc.log` and `request.log` to scan for errors, warnings and notices.

```
import StringIO
import zipfile
f = StringIO.StringIO()
f.write(bytearray(binary_body))
# if zipfile.is_zipfile(f) returns True at thiss point
memory_zip = ZipFile(f)
zip_content = {name: memory_zip.read(name) for name in memory_zip.namelist()}
oracc_log = zip_content['oracc.log']
request_log = zip_content['request.log']
```
